// File generated by FlutterFire CLI — replace by running:
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// Until then this stub lets the project compile. Firebase Auth will not work
// until you run `flutterfire configure` and overwrite this file.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Placeholder — overwritten by `flutterfire configure`.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVeP4YHDGYOXda7Xi0yRyBtUeNMBUggPU',
    appId: '1:119966215010:android:9b8c4d9eda6be49b55da3b',
    messagingSenderId: '119966215010',
    projectId: 'turanta-app',
    storageBucket: 'turanta-app.firebasestorage.app',
  );
  /// Placeholder — overwritten by `flutterfire configure`.

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOmsa5cu1lSCLD6mK7kPPyjuWR9gd79tY',
    appId: '1:119966215010:ios:b4e15401e481c53c55da3b',
    messagingSenderId: '119966215010',
    projectId: 'turanta-app',
    storageBucket: 'turanta-app.firebasestorage.app',
    iosBundleId: 'com.turanta.turantaXpert',
  );
}
